#! /bin/bash

CURRENT_VERSION=0.0.0
INSTALL_PREFIX=/usr
BASE_NAME=`basename "$0"`
INSTALL_ARCH=$(uname -m)
CONFIG_FILE=/etc/install-snuglinux.conf
PO_DIR=${INSTALL_PREFIX}/share/snuglinux
DIR_CHROOT=/mnt
TMP_DIR=/tmp/snuglinux


if ! [ -f ${PO_DIR}/install-snuglinux.func ]; then
  case $lang in
       ru) echo -e "\e[31mОшибка:\e[0m не найден файл install-snuglinux.func в '${PO_DIR}'!!!";;
       uk) echo -e "\e[31mПомилка:\e[0m не знайдений файл install-snuglinux.func у '${PO_DIR}'!!!";;
       *)  echo -e "\e[31mError:\e[0m file install-snuglinux.func not found in '${PO_DIR}'!!!";;
  esac
  exit 1
else
   source ${PO_DIR}/install-snuglinux.func
fi

system_language

set_options $*

if [[ $EUID -ne 0 ]]; then
   show_message I_M_NOT_ROOT
   exit 1
fi

ping_server
if [ "$?" = 1 ]; then
   exit 1;
fi

edit_pacman_conf;

download_updates_func;

checking_installed_packages;

select_type;

preparation_disk;

install_basic_packages;

fix_system_chroot;

install_type;

install_video_driver;

install_network_manager;

generating_fstab;

creating_bootable_ram_disk;

install_bootloader;

enter_localtime;

enter_hostname;

set_password_user "root";

add_users;

clean_install_files;

sync

umount_part

system_reboot
