#! /bin/bash

CURRENT_VERSION=0.0.0
INSTALL_PREFIX=/usr
PO_DIR=${INSTALL_PREFIX}/share/snuglinux

if ! [ -f ${PO_DIR}/install-snuglinux.func ]; then
  case $lang in
       ru) echo -e "\e[31mОшибка:\e[0m не найден файл install-snuglinux.func в '${PO_DIR}'!!!";;
       uk) echo -e "\e[31mПомилка:\e[0m не знайдений файл install-snuglinux.func у '${PO_DIR}'!!!";;
       *)  echo -e "\e[31mError:\e[0m file install-snuglinux.func not found in '${PO_DIR}'!!!";;
  esac
  exit 1
else
   source ${PO_DIR}/install-snuglinux.func
fi

system_language

# install-partition.func
if [ -f "${PO_DIR}/install-partition.func" ]; then
   source  "${PO_DIR}/install-partition.func"
else
   show_message FILE_NOT_FOUND "${PO_DIR}/install-partition.func"
   exit 1
fi

# install-video.func
if [ -f "${PO_DIR}/install-video.func" ]; then
   source "${PO_DIR}/install-video.func"
else
   show_message FILE_NOT_FOUND "${PO_DIR}/install-video.func"
   exit 1
fi

set_options $*

if [[ $EUID -ne 0 ]]; then
   show_message I_M_NOT_ROOT
   exit 1
fi

ping_server
if [ "$?" = 1 ]; then
   exit 1;
fi

edit_pacman_conf "/etc";

edit_pacman_mirrorlist "/etc";

pacman_key_init;

checking_installed_packages;

download_updates_func;

select_type;

preparation_disk;

install_basic_packages;

chroot_setup;

fix_system_chroot;

install_type_pkg;

install_devices_pkg;

install_video_driver;

install_network_manager;

generating_fstab;

creating_bootable_ram_disk;

install_bootloader;

enter_localtime;

enter_hostname;

set_password_user "root";

add_users;

clean_install_files;

sync

umount_part "/mnt"

system_reboot
