#! /bin/bash

CURRENT_VERSION=0.0.3
INSTALL_PREFIX=/usr
BASE_NAME=`basename "$0"`
REAL_ARCH=$(uname -m)
PO_DIR=${INSTALL_PREFIX}/share/snuglinux
CONFIG_FILE=/etc/install-snuglinux.conf

if ! [ -f ${PO_DIR}/install-snuglinux.func ]; then
  case $lang in
       ru) echo -e "\e[31mОшибка:\e[0m не найден файл install-snuglinux.func в '${PO_DIR}'!!!";;
       uk) echo -e "\e[31mПомилка:\e[0m не знайдений файл install-snuglinux.func у '${PO_DIR}'!!!";;
       *)  echo -e "\e[31mError:\e[0m file install-snuglinux.func not found in '${PO_DIR}'!!!";;
  esac
  exit 1
else
   . ${PO_DIR}/install-snuglinux.func
fi

system_language

set_options $*

if [[ $EUID -ne 0 ]]; then
   show_message I_M_NOT_ROOT
   exit 1
fi

ping_server
if [ "$?" = 1 ]; then
   exit 1;
fi

pacman -Sy

NOT_INSTALL_PKG=$(not_installed_pkg "arch-install-scripts wget sed")
if [ -n "$NOT_INSTALL_PKG" ] ; then
   show_message PACKAGE_NOT_INSTALLED "$NOT_INSTALL_PKG"
   exit 1;
fi

select_type

preparation_disk

edit_pacman_conf "/etc/pacman.conf"

show_message INSTALLING_BASIC_PACKAGES
pacstrap /mnt base
if [ "$?" != 0 ]; then
   show_message FAILED_INSTALL_PACKAGE "base"
   exit 1;
fi

system_language "/mnt"

edit_pacman_conf "/mnt/etc/pacman.conf"

install_type

install_video_driver

install_network_manager

generating_fstab

creating_bootable_ram_disk

install_grub

enter_localtime

enter_hostname

set_password_user "root"

add_users

show_message PRESS_ANY_KEY_TO_REBOOT
read
reboot